export const en = {
  app: { name: 'FileHarbor', workspace: 'Workspace', uploads: 'Uploads', settings: 'Settings', signOut: 'Sign out' },
  login: { title: 'Welcome back', subtitle: 'Sign in to manage this FileHarbor workspace.', username: 'Username', password: 'Password', signIn: 'Sign in', invalid: 'Unable to sign in. Check your credentials and try again.' },
  workspace: { root: 'Root', refresh: 'Refresh', newFolder: 'New folder', newFile: 'New file', upload: 'Upload', dropFiles: 'Drop files to upload', empty: 'This folder is empty', emptyTitle: 'Nothing here yet', emptyHint: 'Drop files here, or use Upload to add the first item.', selectAll: 'Select all', selected: '{count} selected', name: 'Name', size: 'Size', modified: 'Modified', actions: 'Actions', readOnly: 'This workspace is read-only.', uploadsOnly: 'This workspace accepts uploads only.', truncated: 'Only the first 100 safe entries are shown.' },
  appearance: { switchToLight: 'Switch to light theme', switchToDark: 'Switch to dark theme', switchToSystem: 'Follow system appearance' },
  action: { open: 'Open', download: 'Download', preview: 'Preview', edit: 'Edit', properties: 'Properties', rename: 'Rename', move: 'Move', copy: 'Copy', delete: 'Delete', archive: 'Archive', extract: 'Extract', checksum: 'Checksum', cancel: 'Cancel', cancelUpload: 'Cancel upload', save: 'Save', close: 'Close', retry: 'Retry', pause: 'Pause', resume: 'Resume', remove: 'Remove', chooseFolder: 'Choose folder', confirm: 'Confirm', batchDownload: 'Download ZIP' },
  dialog: { newFolder: 'Create folder', newFile: 'Create file', rename: 'Rename item', deleteTitle: 'Delete item?', deleteText: 'This cannot be undone.', itemName: 'Name', folderName: 'Folder name', fileName: 'File name', newName: 'New name', destination: 'Destination', confirmDelete: 'Delete {name}?', confirmDeleteBatch: 'Delete {count} items?', confirmDiscard: 'Discard unsaved changes?', typeToConfirm: 'Type DELETE to confirm.', discard: 'Discard' },
  properties: { title: 'Properties', type: 'Type', location: 'Location', size: 'Size', modified: 'Modified', permissions: 'Permissions', contents: 'Contents', incomplete: 'Some items were not counted.' },
  upload: { title: 'Upload queue', addFiles: 'Add files', waiting: 'Waiting', hashing: 'Hashing', uploading: 'Uploading', paused: 'Paused', completed: 'Completed', failed: 'Needs attention', cancelled: 'Cancelled', sourceChanged: 'The selected file does not match the original upload.', resumeHint: 'To resume after a reload, choose the original file again.', allDone: 'All uploads are complete.' },
  editor: { title: 'Edit file', unsaved: 'Unsaved changes', save: 'Save changes', saved: 'Saved', tooLarge: 'This file is too large to edit.', discard: 'Discard unsaved changes?', reload: 'Reload file', loading: 'Loading editor…', languageHint: 'Press Ctrl+S to save.' },
  error: { generic: 'Something went wrong. Please try again.', unauthenticated: 'Your session has ended. Sign in again.', csrf_invalid: 'This request could not be verified. Refresh and try again.', invalid_request: 'Check the highlighted fields and try again.', invalid_credentials: 'Unable to sign in. Check your credentials and try again.', rate_limited: 'Too many sign-in attempts. Please wait and try again.', destination_exists: 'An item with this name already exists.', source_changed: 'This item changed before the operation could be completed.', network_error: 'Network error. Check your connection and retry.' }
};

export type Translation = typeof en;

export const zh: Translation = {
  app: { name: 'FileHarbor', workspace: '工作区', uploads: '上传', settings: '设置', signOut: '退出登录' },
  login: { title: '欢迎回来', subtitle: '登录以管理此 FileHarbor 工作区。', username: '用户名', password: '密码', signIn: '登录', invalid: '无法登录。请检查凭据后重试。' },
  workspace: { root: '根目录', refresh: '刷新', newFolder: '新建文件夹', newFile: '新建文件', upload: '上传', dropFiles: '拖放文件以上传', empty: '此文件夹为空', emptyTitle: '这里还没有内容', emptyHint: '拖放文件到此处，或使用上传按钮添加第一个项目。', selectAll: '全选', selected: '已选择 {count} 项', name: '名称', size: '大小', modified: '修改时间', actions: '操作', readOnly: '此工作区为只读。', uploadsOnly: '此工作区仅接受上传。', truncated: '仅显示前 100 个安全项目。' },
  appearance: { switchToLight: '切换为浅色主题', switchToDark: '切换为深色主题', switchToSystem: '跟随系统外观' },
  action: { open: '打开', download: '下载', preview: '预览', edit: '编辑', properties: '属性', rename: '重命名', move: '移动', copy: '复制', delete: '删除', archive: '压缩', extract: '解压', checksum: '校验和', cancel: '取消', cancelUpload: '取消上传', save: '保存', close: '关闭', retry: '重试', pause: '暂停', resume: '继续', remove: '移除', chooseFolder: '选择文件夹', confirm: '确认', batchDownload: '下载 ZIP' },
  dialog: { newFolder: '创建文件夹', newFile: '创建文件', rename: '重命名项目', deleteTitle: '删除项目？', deleteText: '此操作无法撤销。', itemName: '名称', folderName: '文件夹名称', fileName: '文件名', newName: '新名称', destination: '目标位置', confirmDelete: '删除 {name}？', confirmDeleteBatch: '删除 {count} 项？', confirmDiscard: '放弃未保存的修改？', typeToConfirm: '请输入 DELETE 以确认。', discard: '放弃' },
  properties: { title: '属性', type: '类型', location: '位置', size: '大小', modified: '修改时间', permissions: '权限', contents: '内容', incomplete: '部分项目未计入。' },
  upload: { title: '上传队列', addFiles: '添加文件', waiting: '等待中', hashing: '正在计算哈希', uploading: '上传中', paused: '已暂停', completed: '已完成', failed: '需要处理', cancelled: '已取消', sourceChanged: '所选文件与原始上传文件不匹配。', resumeHint: '刷新后要继续上传，请重新选择原始文件。', allDone: '所有上传均已完成。' },
  editor: { title: '编辑文件', unsaved: '有未保存的修改', save: '保存更改', saved: '已保存', tooLarge: '此文件过大，无法编辑。', discard: '要放弃未保存的修改吗？', reload: '重新加载文件', loading: '正在加载编辑器…', languageHint: '按 Ctrl+S 保存。' },
  error: { generic: '发生错误，请重试。', unauthenticated: '登录已过期，请重新登录。', csrf_invalid: '无法验证此请求。请刷新页面后重试。', invalid_request: '请检查标记的字段后重试。', invalid_credentials: '无法登录。请检查凭据后重试。', rate_limited: '登录尝试过多，请稍后再试。', destination_exists: '同名项目已存在。', source_changed: '操作完成前项目已发生变化。', network_error: '网络错误。请检查连接后重试。' }
};